from pathlib import Path
import logging, hashlib, subprocess, platform, shutil, os, time, atexit, importlib

from tomlkit import document, nl, table, comment
import patoolib

logging.basicConfig(format='%(asctime)s : %(message)s', level=logging.DEBUG)
log = logging.getLogger(__name__)

def check_dossier_tree() -> None:
	# TODO actually make this useful by creating necesarry folders and setting up dossier and such
	# look in base/ and quit if there's nothing in there 
	base_dir = Path.cwd() / 'base'
	base_files = sorted(base_dir.glob('*'))
	if not base_files:
		return 1

def setup_dossier_tree() -> None:
	get_work_directory('base').mkdir(exist_ok=True)
	get_work_directory('mods').mkdir(exist_ok=True)
	Path(Path.cwd() / 'config.toml').touch()
	with open('config.toml', 'w') as f:
		config = document()
		config.add(comment(f'Config file for Dossier, generated by Dossier'))
		config.add(comment(f'Edit with caution...'))

		config.add(nl())