from pathlib import Path
from typing import Union
from src import log
import time

from src.utils.game_info import get_py_script_path

import tomli, tomlkit
from tomlkit import comment, document, table

def create_game_config(game_path: Path) -> None:
	config_path = game_path / 'game' / 'config.toml'
	py_script = get_py_script_path(game_path)

	doc = document()
	doc.add(comment(f'Config file generated by Dossier, for {py_script.stem}. Edit with causion!'))
	info = table()
	if game_path.name == 'base':
		info.add('nickname', 'Doki Doki Literature Club')
	else:
		info.add('nickname', '')
	info.add('date_created', time.time())
	info.add('date_last_played', 0)
	info.add('playtime', 0)
	doc.add('info', info)
	options = table()
	options.add('renpy_save_dir', '')
	options.add('renpy_save_slot', 1)
	options.add('custom_save_dir', '')
	options.add('skip_splash_scr', '')
	options.add('skip_main_menu', '')
	options.add('discord_rpc', '')
	doc.add('options', options)

	with open(config_path, 'w') as f:
		tomlkit.dump(doc, f)
	log.debug('Created "config.toml"')

def set_game_config_value(game_path: Path, key: str, value: Union[bool, int, float, str]) -> None:
	config_path = game_path / 'game' / 'config.toml'
	if not config_path.exists():
		raise FileNotFoundError(f'{get_py_script_path(game_path).stem}\'s config file does not exist!')

	with open(config_path, 'rb') as f:
		config_data = tomli.load(f)

	if key == 'nickname' or key == 'date_last_played' or key == 'playtime':
		category = 'info'
	else:
		category = 'options'

	config_data[category][key] = value

	with open(config_path, 'w') as f:
		tomlkit.dump(config_data, f)
	log.debug(f'Edited {get_py_script_path(game_path).stem}\'s config! ({key}: {value})')

def parse_game_config(game_path: Path) -> dict:
	dossier_config_path = Path.cwd() / 'config.toml'
	game_config_path = game_path / 'game' / 'config.toml'

	with open(dossier_config_path, 'rb') as f:
		dossier_config_data = tomli.load(f)
	with open(game_config_path, 'rb') as f:
		game_config_data = tomli.load(f)

	for option in ('renpy_save_dir', 'skip_splash_scr', 'skip_main_menu', 'discord_rpc'):
		if game_config_data['options'][option] == '':
			game_config_data['options'][option] = dossier_config_data['default_options'][option]

	return game_config_data
